name: Build Extension

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          # Perkenalan diri ke Git
          git config --global user.email "mahrusali@example.com"
          git config --global user.name "Mahrus Ali"
          
          # MATIKAN FITUR SIGNING (Solusi Error GPG)
          git config --global commit.gpgsign false
          git config --global tag.gpgsign false
          
          # Jalankan update
          chmod +x update-deps.sh
          ./update-deps.sh

      - name: Build Extension with Ant
        run: ant extensions

      - name: Upload AIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BaruLagi-Extension
          path: out/*.aix
